language: node_js
sudo: false
dist: trusty
node_js: stable
addons:
  firefox: latest
  chrome: stable
cache:
  directories:
  - node_modules
before_script:
- npm install -g bower web-component-tester
- bower install
script:
- xvfb-run ./node_modules/.bin/wct --configFile wct.conf-app.js
- xvfb-run ./node_modules/.bin/wct --configFile wct.conf-element.js
- cd polymer_3
- npm i
- xvfb-run node_modules/.bin/wct